"use client";

import { useState, useEffect } from "react";
import MenuFormModal from "@/components/MenuFormModal";

// Shadcn UI components
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "@/components/ui/alert-dialog";
import { useToast } from "@/hooks/use-toast"; // Assuming this is generated by shadcn
import { Toaster } from "@/components/ui/toaster";

// --- Interfaces (assuming they are defined elsewhere or here) ---
interface RawMenuItem {
  Menu: string;
  "sub-menu": string;
  titulo: string;
  descripcion: string;
  Precio: string;
  "url de imagen": string;
  id?: string; // Make id optional for existing raw data, but will be added for new items
}

interface MenuItem {
  id: string; // Now mandatory for MenuItem
  nombre: string;
  detalles?: string;
  precio: number;
  image: string | null;
  category: string;
  subCategory: string;
}

// --- Helper Functions ---

const transformToRawMenu = (menuItems: MenuItem[]): RawMenuItem[] => {
  return menuItems.map((item) => ({
    Menu: item.category,
    "sub-menu": item.subCategory,
    titulo: item.nombre,
    descripcion: item.detalles || "",
    Precio: `${item.precio.toFixed(2)}`,
    "url de imagen": item.image || "/images/menu/logonala-menu.avif",
    id: item.id, // Include the id
  }));
};

// --- Component ---

export default function AdminMenuPage() {
  const [menuItems, setMenuItems] = useState<MenuItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [itemToEdit, setItemToEdit] = useState<MenuItem | null>(null);
  const { toast } = useToast(); // Initialize toast

  // Fetch and transform menu data on initial load
  useEffect(() => {
    const fetchAndTransformMenu = async () => {
      try {
        const res = await fetch("/api/menu");
        if (!res.ok) throw new Error("Failed to fetch menu");
        const rawData = await res.json();

        const transformedItems: MenuItem[] = [];
        for (const category in rawData) {
          for (const subCategory in rawData[category]) {
            for (const item of rawData[category][subCategory]) {
              transformedItems.push({
                ...item,
                id: item.id || crypto.randomUUID(), // Use existing ID or generate new one
                category,
                subCategory,
              });
            }
          }
        }
        setMenuItems(transformedItems);
      } catch (err: unknown) {
        setError((err as Error).message);
        toast({
          title: "Error",
          description: `Error al cargar el menú: ${(err as Error).message}`,
          variant: "destructive",
        });
      } finally {
        setLoading(false);
      }
    };

    fetchAndTransformMenu();
  }, [toast]);

  const handleOpenModal = (item: MenuItem | null = null) => {
    setItemToEdit(item);
    setIsModalOpen(true);
  };

  const handleCloseModal = () => {
    setIsModalOpen(false);
    setItemToEdit(null);
  };

  const handleSave = async (itemToSave: MenuItem) => {
    // If it's a new item (no existing ID or a temporary one), assign a real UUID
    if (!itemToSave.id || itemToSave.id.startsWith("item-")) {
      itemToSave.id = crypto.randomUUID();
    }

    const newItems = [...menuItems];
    const index = newItems.findIndex((item) => item.id === itemToSave.id);

    if (index > -1) {
      newItems[index] = itemToSave; // Update existing
    } else {
      newItems.push(itemToSave); // Add new
    }

    // Optimistic update
    setMenuItems(newItems);
    handleCloseModal();

    // Persist changes to the server
    try {
      const rawMenu = transformToRawMenu(newItems);
      const res = await fetch("/api/menu/update", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(rawMenu),
      });

      if (!res.ok) {
        throw new Error("Failed to save menu");
      }
      toast({
        title: "Éxito",
        description: "Platillo guardado exitosamente.",
      });
    } catch (error: unknown) {
      console.error(error);
      // TODO: Implement rollback on failure
      toast({
        title: "Error",
        description: `Error al guardar el platillo: ${(error as Error).message}`,
        variant: "destructive",
      });
    }
  };

  const handleDelete = async (id: string) => {
    const originalItems = [...menuItems]; // For rollback
    const newItems = menuItems.filter((item) => item.id !== id);
    setMenuItems(newItems); // Optimistic update

    try {
      const rawMenu = transformToRawMenu(newItems);
      const res = await fetch("/api/menu/update", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(rawMenu),
      });

      if (!res.ok) {
        throw new Error("Failed to delete item");
      }
      toast({
        title: "Éxito",
        description: "Platillo eliminado exitosamente.",
      });
    } catch (err: unknown) {
      console.error(err);
      setMenuItems(originalItems); // Rollback
      toast({
        title: "Error",
        description: `Error al eliminar el platillo: ${(err as Error).message}`,
        variant: "destructive",
      });
    }
  };

  if (loading) return <div>Loading menu...</div>;
  if (error) return <div>Error: {error}</div>;

  // Group menu items by category
  const menuByCategory = menuItems.reduce(
    (acc, item) => {
      if (!acc[item.category]) {
        acc[item.category] = [];
      }
      acc[item.category].push(item);
      return acc;
    },
    {} as Record<string, MenuItem[]>,
  );

  return (
    <div className="p-4">
      <div className="flex justify-between items-center mb-4">
        <h1 className="text-2xl font-bold">Menu Management</h1>
        <Button onClick={() => handleOpenModal()}>Agregar Nuevo Platillo</Button>
      </div>

      <Accordion type="single" collapsible className="w-full">
        {Object.entries(menuByCategory).map(([category, items]) => (
          <AccordionItem value={category} key={category}>
            <AccordionTrigger className="text-xl font-semibold">
              {category}
            </AccordionTrigger>
            <AccordionContent>
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                {items.map((item) => (
                  <Card key={item.id}>
                    <CardHeader>
                      <CardTitle>{item.nombre}</CardTitle>
                      <CardDescription>{item.detalles}</CardDescription>
                    </CardHeader>
                    <CardContent>
                      <img
                        src={item.image || "/images/menu/logonala-menu.avif"}
                        alt={item.nombre}
                        className="w-full h-48 object-cover rounded-md mb-2"
                      />
                      <p className="text-lg font-bold">
                        ${item.precio.toFixed(2)}
                      </p>
                      <p className="text-sm text-gray-500">
                        {item.subCategory}
                      </p>
                    </CardContent>
                    <CardFooter className="flex justify-end space-x-2">
                      <Button
                        variant="outline"
                        onClick={() => handleOpenModal(item)}
                      >
                        Edit
                      </Button>
                      <AlertDialog>
                        <AlertDialogTrigger asChild>
                          <Button variant="destructive">Delete</Button>
                        </AlertDialogTrigger>
                        <AlertDialogContent>
                          <AlertDialogHeader>
                            <AlertDialogTitle>
                              Are you absolutely sure?
                            </AlertDialogTitle>
                            <AlertDialogDescription>
                              This action cannot be undone. This will
                              permanently delete the menu item.
                            </AlertDialogDescription>
                          </AlertDialogHeader>
                          <AlertDialogFooter>
                            <AlertDialogCancel>Cancel</AlertDialogCancel>
                            <AlertDialogAction
                              onClick={() => handleDelete(item.id)}
                            >
                              Continue
                            </AlertDialogAction>
                          </AlertDialogFooter>
                        </AlertDialogContent>
                      </AlertDialog>
                    </CardFooter>
                  </Card>
                ))}
              </div>
            </AccordionContent>
          </AccordionItem>
        ))}
      </Accordion>

      <MenuFormModal
        isOpen={isModalOpen}
        onClose={handleCloseModal}
        onSave={handleSave}
        itemToEdit={itemToEdit}
      />
      {/* Toaster component for displaying toasts */}
      <Toaster />
    </div>
  );
}
